[package]
name = "il2cpp_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = {version="0.62.2", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_LibraryLoader"]}


[lib]
crate-type = ["cdylib"]

[profile.dev]
lto=true
